// Portfolio data — single source of truth
export const siteConfig = {
  name: "Pruthvi Raj B",
  title: "ISE Graduate · Aspiring AI Operator",
  role: "Full Stack & Android Developer",
  bio: "Information Science & Engineering graduate with a strong interest in Artificial Intelligence, business operations, and emerging technologies. I focus on leveraging modern digital tools, analytical thinking, and effective communication to deliver high-quality outcomes.",
  bio2: "My portfolio includes Shale-Namma Pride — a bilingual school communication system deployed for real schools — and Nexus Learn, a smart management platform integrating AI-powered report generation.",
  bio3: 'A results-oriented professional who adapts quickly to new technologies, as demonstrated by my "EXCELLENT" internship rating at MindMatrix — delivering all modules ahead of schedule.',
  location: "Chikkaballapur, Karnataka, India",
  email: "pruthviraj.b.in@gmail.com",
  phone: "+91 97406 34537",
  linkedin: "https://linkedin.com/in/pruthvirajbc",
  github: "https://github.com/pruthviraj-b",
  whatsapp: "+91 97406 34537",
  whatsappUrl: "https://wa.me/919740634537",
  liveProject: "https://shalenammapride-b4fc8.web.app",
  available: true,
};

export const skills = [
  {
    category: "Mobile Development",
    icon: "📱",
    color: "from-violet-500/20 to-indigo-500/10 border-violet-500/30",
    accent: "text-violet-400",
    items: ["Kotlin", "Jetpack Compose", "Android Studio", "Firebase Auth", "Firestore", "Firebase Realtime DB", "Firebase Hosting"],
  },
  {
    category: "Web Technologies",
    icon: "🌐",
    color: "from-cyan-500/20 to-blue-500/10 border-cyan-500/30",
    accent: "text-cyan-400",
    items: ["React.js", "Next.js 14", "TypeScript", "Node.js", "Express.js", "REST API Design", "Prisma ORM"],
  },
  {
    category: "AI / Generative AI",
    icon: "🤖",
    color: "from-emerald-500/20 to-teal-500/10 border-emerald-500/30",
    accent: "text-emerald-400",
    items: ["OpenAI API", "Prompt Engineering", "Generative AI", "LLMs", "Google AI Studio", "Google Cloud Labs"],
  },
  {
    category: "Databases & Backend",
    icon: "🗄️",
    color: "from-orange-500/20 to-amber-500/10 border-orange-500/30",
    accent: "text-orange-400",
    items: ["Supabase", "PostgreSQL", "Firebase Realtime DB", "Firestore"],
  },
  {
    category: "Languages",
    icon: "💻",
    color: "from-pink-500/20 to-rose-500/10 border-pink-500/30",
    accent: "text-pink-400",
    items: ["Kotlin", "Java", "Python", "SQL", "HTML", "CSS"],
  },
  {
    category: "Tools & Platforms",
    icon: "🛠️",
    color: "from-slate-500/20 to-zinc-500/10 border-slate-500/30",
    accent: "text-slate-400",
    items: ["Git", "GitHub", "Postman", "VS Code", "Eclipse", "Windows"],
  },
];

export const projects = [
  {
    id: 1,
    name: "Shale-Namma Pride",
    subtitle: "School Communication System",
    icon: "🏫",
    live: true,
    liveUrl: "https://shalenammapride-b4fc8.web.app",
    githubUrl: "https://github.com/pruthviraj-b/ShalenammaPride",
    secondaryGithubUrl: "https://github.com/pruthviraj-b/ShalenammaPrideweb",
    apkUrl: "https://github.com/pruthviraj-b/ShalenammaPride/raw/main/Shale-Namma-Pride-Premium-Auth.apk",
    role: "Solo Developer · Android App + Web Portal",
    context: "Schools lacked a digital channel for daily communication — especially in Kannada-speaking communities.",
    description: "A bilingual (English & Kannada) school communication system where teachers update meal menus and announcements from an Android app — and parents see changes live on a website instantly.",
    bullets: [
      "Built bilingual real-time school communication with Android app and live web portal.",
      "Implemented real-time sync using Firebase — teacher updates instantly reflect for parents.",
      "Role-based access control: teachers post, parents view-only.",
      "Currently in production use by real schools.",
    ],
    tech: ["Kotlin", "Jetpack Compose", "React.js", "Firebase", "Firebase Auth", "Firebase Hosting"],
    gradient: "from-violet-600 to-indigo-600",
    featured: true,
  },
  {
    id: 2,
    name: "Nexus Learn",
    subtitle: "AI-Powered School Management",
    icon: "🎓",
    live: false,
    liveUrl: null,
    githubUrl: "https://github.com/pruthviraj-b/nexus-learn",
    role: "Solo Developer · Smart Management Platform",
    context: "Schools needed a single platform for admins, students, and parents — with AI-powered report generation.",
    description: "A smart school management system where Admins manage operations, Students track learning, and Parents stay updated — all from one platform with AI-generated performance reports.",
    bullets: [
      "Multi-role dashboards for Admins, Students, and Parents.",
      "OpenAI API integration auto-generates student performance reports.",
      "Real-time messaging using Supabase subscriptions.",
      "Built with Next.js 14, TypeScript, and Supabase (PostgreSQL).",
    ],
    tech: ["Next.js 14", "TypeScript", "Supabase", "PostgreSQL", "OpenAI API", "Generative AI"],
    gradient: "from-emerald-600 to-teal-600",
    featured: false,
  },
  {
    id: 3,
    name: "JATHIN'S Learning Hub",
    subtitle: "Home Tuition Platform",
    icon: "📚",
    live: false,
    liveUrl: null,
    githubUrl: "https://github.com/pruthviraj-b/JATHIN-S-LEARNING-HUB",
    role: "Solo Developer · Full-Stack Web App",
    context: "Home tutors had no dedicated tool to track sessions, schedules, and student progress.",
    description: "A full-stack tuition management platform with separate dashboards for teachers and students to track sessions, progress, and schedules.",
    bullets: [
      "Separate dashboards for teachers and students.",
      "RESTful backend using Node.js, Express.js, and Prisma ORM.",
      "Modern, responsive Next.js frontend.",
    ],
    tech: ["Next.js", "Node.js", "Express.js", "Prisma ORM", "REST API"],
    gradient: "from-orange-600 to-amber-600",
    featured: false,
  },
];

export const experience = {
  role: "Android Developer Intern",
  company: "MindMatrix Learning",
  companyFull: "CL Infotech Pvt. Ltd. (VTU MoU Partner)",
  period: "Feb 2026 – May 2026",
  location: "Online · Bengaluru",
  program: "Android App Development using Generative AI — VTU Internship Portal",
  rating: "EXCELLENT",
  bullets: [
    { num: "01", text: "Developed Android application features using <strong>Kotlin</strong> and <strong>Jetpack Compose</strong> during a 3-month internship." },
    { num: "02", text: "Designed and implemented <strong>user interface screens</strong>, navigation flows, and form validations." },
    { num: "03", text: "Integrated <strong>Firebase Authentication</strong> and worked with backend services for user management." },
    { num: "04", text: "Tested functionality, identified and fixed UI and logic issues, and improved overall user experience." },
    { num: "05", text: "Prepared <strong>project documentation</strong> and submitted all assigned modules within deadlines." },
    { num: "06", text: 'Received an <strong>"EXCELLENT"</strong> performance rating for consistent delivery and engagement.' },
  ],
  tools: ["Kotlin", "Jetpack Compose", "Android Studio", "Firebase Auth", "Google AI Studio", "Google Cloud Labs"],
};

export const education = [
  {
    degree: "B.E. — Information Science & Engineering (Lateral Entry)",
    institution: "SJC Institute of Technology, Chikkaballapur",
    university: "VTU",
    period: "2023 – 2026",
    score: "CGPA: 7.5",
    icon: "🎓",
  },
  {
    degree: "Diploma — Computer Science & Engineering",
    institution: "Chintamani Government Polytechnic",
    university: "DOTE",
    period: "2020 – 2023",
    score: "CGPA: 8.5 — Merit Lateral Entry to B.E.",
    icon: "📜",
  },
  {
    degree: "Secondary School Leaving Certificate (SSLC)",
    institution: "Sir MVM High School",
    university: "KSEEB",
    period: "2020",
    score: "75%",
    icon: "📝",
  },
];

export const certifications = [
  { name: "Python Essentials 1 & 2", org: "Cisco Networking Academy", icon: "🐍", link: "/certificates/Python-Essentials-2.pdf" },
  { name: "Introduction to Cybersecurity", org: "Cisco Networking Academy", icon: "🔐", link: "/certificates/Introduction-to-Cybersecurity.pdf" },
  { name: "DevOps, Cloud & Cyber Security Masterclass", org: "Scaler", icon: "☁️", link: "/certificates/Scaler-DevOps-Cloud.png" },
  { name: "AI & Cloud Fundamentals Workshop", org: "Industry Programme", icon: "🤖" },
  { name: "EXCELLENT Performance Rating", org: "MindMatrix Internship · 2026", icon: "⭐", achievement: true, link: "/internships/MindMatrix-Completion-Letter.pdf" },
  { name: "Lateral Entry to B.E. (Merit-based)", org: "Diploma CGPA 8.5 · VTU", icon: "🏆", achievement: true },
];
